apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name | default .Chart.Name }}
spec:
  selector:
    app: {{ .Values.deployment.name | default .Chart.Name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.deployment.container.port }}
    targetPort: {{ .Values.deployment.container.port }}
  type: ClusterIP