apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Values.deployment.name | default .Chart.Name }}
  namespace: default
spec:
  entryPoints:
  - {{ .Values.traefik.entrypointName }}
  routes:
  - match: HostSNI(`*`)
    services:
    - name: {{ .Values.deployment.name | default .Chart.Name }}
      port: {{ .Values.deployment.container.port }}