deployment:
  name: nb-simple-service
  replicaCount: 1
  container:
    port: 8089
    image: antomer/nb-simple-service
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "512Mi"
traefik:
  entryointName: nbsimpleservice