name: CI/CD task-3/app
on:
  pull_request:
    branches:
      - master
    paths:
      - task-3/app/**
      - .github/workflows/ci-cd.yaml
  push:
    branches:
      - master
    paths:
      - task-3/app/**
      - .github/workflows/ci-cd.yaml
env:
  DOCKER_HUB_REPOSITORY: "antomer/nb-simple-service"
jobs:
  lint-test:
    name: Lint & test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: "task-3/app/.nvmrc"
          cache: "npm"
          cache-dependency-path: task-3/app/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: task-3/app/

      - name: Run lint
        run: npm run lint
        working-directory: task-3/app/

      - name: Run unit test
        run: npm run test
        working-directory: task-3/app/

  build:
    name: Build & push image
    needs: lint-test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set image tag 
        id: set_image_tag
        run: | 
          echo "IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          docker build -t ${DOCKER_HUB_REPOSITORY}:${{ steps.set_image_tag.outputs.IMAGE_TAG }} .
        working-directory: task-3/app/

      - name: Login to Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Push image
        run: |
          docker push ${DOCKER_HUB_REPOSITORY}:${{ steps.set_image_tag.outputs.IMAGE_TAG }}
        working-directory: task-3/app/
  deploy:
    name: Deploy changes
    needs: build
    #if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # workaround, as a output containing commit SHA and providede between GH jobs is false positive detected as an secret https://github.com/community/community/discussions/37942
      - name: Set image tag 
        id: set_image_tag
        run: | 
          echo "IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - uses: azure/setup-helm@v3
        with:
          version: "3.11.2" # default is latest (stable)

      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy using Helm
        working-directory: task-3/app/.deploy/helm/
        run: |
          helm install nb-simple-service-${{ steps.set_image_tag.outputs.IMAGE_TAG }} . --set deployment.container.image=${DOCKER_HUB_REPOSITORY}:${{ steps.set_image_tag.outputs.IMAGE_TAG }} -f values.yaml --wait 
